version: '3.2'

# networks:
#   example:

services:
  server-golang:
    image: server:assessment
    ports:
      - 2565:2565
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      
  # db:
  #   image: postgres:12.12
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: go-example-db
  #   restart: on-failure
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d/
  #   networks:
  #     - integration-test-example